CC = mpicc
RM = /bin/rm
PROG = pingpong pingpong_i

all : ${PROG}

pingpong : pingpong.c
	${CC} -o $@ $^ -O3 -march=native

pingpong_i : pingpong_i.c
	${CC} -o $@ $^ -O3 -march=native

clean :
	${RM} -f ${PROG}